/**
 * Synthetic Command Registration for Claude Code
 * Generated by Synthetic Code Agent: DEVFLOW-CC-INTEGRATION-001
 * Implements slash command registration for /synthetic family commands
 */
export declare function registerSyntheticCommands(): void;
//# sourceMappingURL=synthetic-command-registry.d.ts.map