# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cc_tools_integration_pb2 as cc__tools__integration__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cc_tools_integration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CCToolsIntegrationStub(object):
    """gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateProject = channel.unary_unary(
                '/cc_tools_integration.CCToolsIntegration/ValidateProject',
                request_serializer=cc__tools__integration__pb2.ValidationRequest.SerializeToString,
                response_deserializer=cc__tools__integration__pb2.ValidationResponse.FromString,
                _registered_method=True)
        self.GetProjectMetadata = channel.unary_unary(
                '/cc_tools_integration.CCToolsIntegration/GetProjectMetadata',
                request_serializer=cc__tools__integration__pb2.ValidationRequest.SerializeToString,
                response_deserializer=cc__tools__integration__pb2.ProjectMetadata.FromString,
                _registered_method=True)
        self.AcquireLock = channel.unary_unary(
                '/cc_tools_integration.CCToolsIntegration/AcquireLock',
                request_serializer=cc__tools__integration__pb2.LockRequest.SerializeToString,
                response_deserializer=cc__tools__integration__pb2.LockStatus.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/cc_tools_integration.CCToolsIntegration/ReleaseLock',
                request_serializer=cc__tools__integration__pb2.LockRequest.SerializeToString,
                response_deserializer=cc__tools__integration__pb2.LockStatus.FromString,
                _registered_method=True)
        self.CheckLock = channel.unary_unary(
                '/cc_tools_integration.CCToolsIntegration/CheckLock',
                request_serializer=cc__tools__integration__pb2.LockRequest.SerializeToString,
                response_deserializer=cc__tools__integration__pb2.LockStatus.FromString,
                _registered_method=True)


class CCToolsIntegrationServicer(object):
    """gRPC service definition
    """

    def ValidateProject(self, request, context):
        """Validate project with cc-tools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectMetadata(self, request, context):
        """Get project metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireLock(self, request, context):
        """Acquire lock for project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Release lock for project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckLock(self, request, context):
        """Check lock status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CCToolsIntegrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateProject,
                    request_deserializer=cc__tools__integration__pb2.ValidationRequest.FromString,
                    response_serializer=cc__tools__integration__pb2.ValidationResponse.SerializeToString,
            ),
            'GetProjectMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectMetadata,
                    request_deserializer=cc__tools__integration__pb2.ValidationRequest.FromString,
                    response_serializer=cc__tools__integration__pb2.ProjectMetadata.SerializeToString,
            ),
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=cc__tools__integration__pb2.LockRequest.FromString,
                    response_serializer=cc__tools__integration__pb2.LockStatus.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=cc__tools__integration__pb2.LockRequest.FromString,
                    response_serializer=cc__tools__integration__pb2.LockStatus.SerializeToString,
            ),
            'CheckLock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLock,
                    request_deserializer=cc__tools__integration__pb2.LockRequest.FromString,
                    response_serializer=cc__tools__integration__pb2.LockStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cc_tools_integration.CCToolsIntegration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cc_tools_integration.CCToolsIntegration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CCToolsIntegration(object):
    """gRPC service definition
    """

    @staticmethod
    def ValidateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cc_tools_integration.CCToolsIntegration/ValidateProject',
            cc__tools__integration__pb2.ValidationRequest.SerializeToString,
            cc__tools__integration__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cc_tools_integration.CCToolsIntegration/GetProjectMetadata',
            cc__tools__integration__pb2.ValidationRequest.SerializeToString,
            cc__tools__integration__pb2.ProjectMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cc_tools_integration.CCToolsIntegration/AcquireLock',
            cc__tools__integration__pb2.LockRequest.SerializeToString,
            cc__tools__integration__pb2.LockStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cc_tools_integration.CCToolsIntegration/ReleaseLock',
            cc__tools__integration__pb2.LockRequest.SerializeToString,
            cc__tools__integration__pb2.LockStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cc_tools_integration.CCToolsIntegration/CheckLock',
            cc__tools__integration__pb2.LockRequest.SerializeToString,
            cc__tools__integration__pb2.LockStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
