/**
 * Cross-Platform Synchronizer - Real-time Context Updates
 * Generated by Synthetic Code Agent: DEVFLOW-MEMORY-001
 * Implements <200ms synchronization target
 */
import type { UniversalContextFormat, SyncStatus } from './universal-context-format.js';
export declare class CrossPlatformSynchronizer {
    private storage;
    private conflictResolver;
    private contextOptimizer;
    private eventQueue;
    private isProcessing;
    private syncInterval;
    constructor(dbPath?: string);
    private startSyncProcessor;
    synchronize(context: UniversalContextFormat): Promise<void>;
    getContextById(id: string): Promise<UniversalContextFormat | null>;
    getAllContexts(): Promise<UniversalContextFormat[]>;
    deleteContext(id: string): Promise<void>;
    getSyncStatus(): SyncStatus;
    private addSyncEvent;
    private processSyncQueue;
    private processSyncEvent;
    close(): void;
}
//# sourceMappingURL=cross-platform-synchronizer.d.ts.map