/**
 * Cross-Platform Memory System - Comprehensive Test Suite
 * Generated by Synthetic Code Agent: DEVFLOW-MEMORY-001
 * Tests for Phase 1 completion validation
 */
declare function runCrossPlatformMemoryTests(): Promise<boolean>;
export { runCrossPlatformMemoryTests };
//# sourceMappingURL=cross-platform-memory.test.d.ts.map