/**
 * Universal Context Format for Cross-Platform Memory System
 * Generated by Synthetic Code Agent: DEVFLOW-MEMORY-001
 * Qwen 2.5 Coder 32B - 1,746 tokens processed (fallback from Context Agent)
 */

export interface UniversalContextFormat {
  id: string;
  data: any;
  lastUpdated: Date;
  version: number;
  platform?: string;
  contextType?: 'code' | 'reasoning' | 'architectural' | 'mixed';
  metadata?: {
    tokens?: number;
    cost?: number;
    quality?: number;
    source?: string;
  };
}

export interface ContextSyncEvent {
  type: 'create' | 'update' | 'delete' | 'conflict';
  contextId: string;
  timestamp: Date;
  source: string;
  data?: UniversalContextFormat;
}

export interface SyncStatus {
  lastSync: Date;
  pendingUpdates: number;
  conflicts: number;
  isOnline: boolean;
}