/**
 * Advanced Task Router - Unit Tests
 * Generated by Synthetic Code Agent: DEVFLOW-ROUTER-001
 * Testing implementation with mock coordinator
 */
export declare function runAllTests(): Promise<boolean>;
//# sourceMappingURL=task-router.test.d.ts.map