/**
 * Command Registry for Claude Code Slash Commands
 * Generated by Synthetic Code Agent: DEVFLOW-CC-INTEGRATION-001
 */
export type CommandHandler = (args: string[]) => Promise<void>;
export declare class CommandRegistry {
    private commands;
    registerCommand(commandName: string, handler: CommandHandler): void;
    executeCommand(commandName: string, args: string[]): Promise<boolean>;
    getRegisteredCommands(): string[];
    hasCommand(commandName: string): boolean;
}
export declare const commandRegistry: CommandRegistry;
//# sourceMappingURL=command-registry.d.ts.map