/**
 * DevFlow Claude Code Adapter
 * Generated by Synthetic Code Agent: DEVFLOW-CC-INTEGRATION-001
 * Main entry point for Claude Code integration
 */

// Export command registry
export type { CommandRegistry, CommandHandler } from './command-registry.js';
export { commandRegistry } from './command-registry.js';

// Export synthetic commands
export { SyntheticCommand, syntheticCommand } from './commands/synthetic-command.js';
export { registerSyntheticCommands } from './commands/synthetic-command-registry.js';

// Auto-initialize synthetic commands
import './commands/synthetic-command-registry.js';

console.log('🚀 DevFlow Claude Code Adapter initialized');