/**
 * DevFlow Claude Code Adapter
 * Generated by Synthetic Code Agent: DEVFLOW-CC-INTEGRATION-001
 * Main entry point for Claude Code integration
 */
export { CommandRegistry, commandRegistry, CommandHandler } from './command-registry.js';
export { SyntheticCommand, syntheticCommand } from './commands/synthetic-command.js';
export { registerSyntheticCommands } from './commands/synthetic-command-registry.js';
import './commands/synthetic-command-registry.js';
//# sourceMappingURL=index.d.ts.map